### PR TITLE
Darkbrotherhood

### PR DESCRIPTION
**Pull request by Shadowfen**
Pulled down your latest commits and reworked my champion experience point calculations so it quit outputting rubbish. 
- Got rid of GetPlayerChampionXPMax function because it was doing the same calculation as GetPlayerXPMax when the player is a champion. 
- Used as the upper XP value, the number of xp for the (current champion point level + 1) (as the level we are working towards).

### CODE REVIEW

**Comment by Arthmoor** [comment]
What does that +1 you added on line 137 do?

While I was playing last night it didn't seem to me that the xp was being calculated wrong in some way and agreed with what the game's own UI said when I hovered it in the character menu.

**Comment by Shadowfen** [comment]
Basically, by taking the characters current cp, adding one gives me the
next cp being worked towards. Then convert that value to the xp being
worked toward.

Shadowfen

**Comment by Arthmoor** [comment]
Isn't that basically what this was doing on the old line 144?

GetNumChampionXPInChampionPoint(GetChampionPointsPlayerProgressionCap("player"))

I'm not really all that familiar with how a lot of this works, but it seemed to be fine.

**Comment by Shadowfen** [comment]
Perhaps it only manifests with a toon that is already over the 501 "cap"?

D

**Comment by Shadowfen** [comment]
Theory is that GetChampionPointsPlayerProgressionCap() would stop at 501
(the current usable cap) when I wanted to just find how high xp I need to
get to the next champ point even if I'm working on getting champ point
512.  I was seeing the second number being lower than the first and the
percentage then winding up in the 100+% range - just wrong.
By going with the what my CP + 1 is, I don't care what the current cap
might be since it does not apply for this need.

**Comment by Arthmoor** [comment]
Makes sense. I haven't broken 300 yet myself. I guess it's fine so long as the calculation displays properly when someone is below the cap.

**Comment by 4bitfocus** [comment]
The +1 on line 137 does seem a bit magical. Can you add a comment there on your next commit?

**Pull request merged**
